disabled_rules: # rule identifiers to exclude from running
  - block_based_kvo
  - cyclomatic_complexity
  - file_length
  - for_where
  - force_cast
  - force_try
  - function_body_length
  - identifier_name
  - line_length
  - notification_center_detachment
  - statement_position
  - todo
  - trailing_whitespace
  - type_body_length
  - type_name
  - unused_closure_parameter
